title: Bob Pony Blog
description: The place where you can find information on updates and other stories here.

plugins:
   - jekyll-avatar
   - jekyll-mentions
   - jekyll-sitemap
   - jekyll-feed
   - jekyll-paginate
   - jemoji
permalink: /blog/:categories/:title/
kramdown:
  auto_ids: false
collections:
  - downloads
  - gallery
paginate: 6
paginate_path: "/blog/page:num/"